In [6]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[2],[2]])

# 转置
print (a.T)

# 求逆
print (np.linalg.inv(a))

# 矩阵相乘
print(a @ b)

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 6]
 [14]]


In [3]:
3**0.5/3

0.5773502691896257

In [28]:
# -*- coding: utf-8 -*-
"""
Numeric integration routines
----------------------------
Weights and coordinates for Gauss-Legendre quadrature [WGAUSS]_. The
values for triangles is presented in section 5.5 of Bathe book [BATHE]_.

References
----------
.. [WGAUSS] Wikipedia contributors. "Gaussian quadrature." Wikipedia,
   The Free Encyclopedia, 2 Nov.  2015. Web. 25 Dec. 2015.
   url: https://en.wikipedia.org/wiki/Gaussian_quadrature
.. [BATHE] Bathe, Klaus-Jürgen. Finite element procedures. Prentice Hall,
   Pearson Education, 2006.
"""
from itertools import product
import numpy as np


#%% General
def gauss_1d(npts):
    """Return Gauss points and weights for Gauss quadrature in 1D

    Parameters
    ----------
    npts : int
      Number of quadrature points.

    Returns
    -------
    wts : ndarray
      Weights for the Gauss-Legendre quadrature.
    pts : ndarray
      Points for the Gauss-Legendre quadrature.
    """
    if npts == 2:
        pts = [-0.577350269189625764, 0.577350269189625764]
        wts = [1.00000000000000000, 1.00000000000000000]
    elif npts == 3:
        pts = [-0.774596669241483377, 0, 0.774596669241483377]
        wts = [0.555555555555555556, 0.888888888888888889,
               0.555555555555555556]
    elif npts == 4:
        pts = [-0.861136311594052575, -0.339981043584856265,
               0.339981043584856265, 0.861136311594052575]
        wts = [0.347854845137453857, 0.652145154862546143,
               0.652145154862546143, 0.347854845137453857]  
    else:
        msg = "The number of points should be in [2, 10]"
        raise ValueError(msg)

    return pts, wts


def gauss_nd(npts, ndim=2):
    """
    Return Gauss points and weights for Gauss quadrature in
    an ND hypercube.

    Parameters
    ----------
    npts : int
      Number of quadrature points.

    Returns
    -------
    nd_wts : ndarray
      Weights for the Gauss-Legendre quadrature.
    nd_pts : ndarray
      Points for the Gauss-Legendre quadrature.
    """
    pts, wts = gauss_1d(npts)
    nd_pts = np.array(list(product(pts, repeat=ndim)))
    nd_wts = product(wts, repeat=ndim)
    nd_wts = [np.prod(nd_wt) for nd_wt in nd_wts]
    return nd_pts, nd_wts



In [34]:
pts, wts = gauss_1d(2)
print(pts,wts)
nd_pts = np.array(list(product(pts, repeat=2)))
print(nd_pts)
nd_wts = product(wts, repeat=2)
print(nd_wts)
nd_wts = [np.prod(nd_wt) for nd_wt in nd_wts]
print(nd_wts)

[-0.5773502691896257, 0.5773502691896257] [1.0, 1.0]
[[-0.57735027 -0.57735027]
 [-0.57735027  0.57735027]
 [ 0.57735027 -0.57735027]
 [ 0.57735027  0.57735027]]
[(1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0)]


my assemble:
array([[ 1.,  0.,  0.,  0., 13., 14., 11., 12.],
       [ 0.,  0.,  2.,  0.,  7.,  8., 13., 14.],
       [11., 12., 13., 14.,  9., 10.,  5.,  6.],
       [13., 14.,  7.,  8.,  3.,  4.,  9., 10.]])

In [21]:
array([[ 0, -1, -1, -1, 12, 13, 10, 11,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [-1, -1,  1, -1,  6,  7, 12, 13,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [10, 11, 12, 13,  8,  9,  4,  5,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [12, 13,  6,  7,  2,  3,  8,  9,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0]])

[0.3333333333333333,
 -0.3333333333333333,
 -0.3333333333333333,
 0.3333333333333333]

In [23]:
np.prod([0.3,0.4])

0.12